#!/bin/sh
# postinst script for ip2w

set -xe

echo "Creating python virtual environment..."
mkdir -p /var/pyvenvs/ip2w
python3.9 -m venv /var/pyvenvs/ip2w

echo "Upgrading pip..."
/var/pyvenvs/ip2w/bin/pip3.9 install --upgrade pip

echo "Installing python libs from requirements.txt..."
/var/pyvenvs/ip2w/bin/pip3.9 install -r /usr/local/ip2w/requirements.txt

if [ -e /etc/nginx/conf.d/default.conf ] ; then 
    echo "Moving /etc/nginx/conf.d/default.conf to /etc/nginx/conf.d/default.conf.orig..."
    mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.orig 
fi

echo "Adding link /etc/systemd/system/ip2w.service -> /usr/lib/systemd/system/ip2w.service..."
ln -s /usr/lib/systemd/system/ip2w.service /etc/systemd/system/ip2w.service

echo "Enabling ip2w service..."
systemctl enable ip2w
systemctl enable nginx

exit 0